parameters:

    vig.cms.super_admin_role: 'ROLE_SUPER_ADMIN'
    vig.cms.simple_text_controller: 'VideInfraCMSBundle:SimpleText:show'
    vig.cms.simple_text_template: 'VideInfraCMSBundle:SimpleText:show.html.twig'

    vig.cms.block_controller: 'VideInfraCMSBundle:Block:show'
    vig.cms.block_template: 'VideInfraCMSBundle:Block:show.html.twig'
    vig.cms.text.block.template: 'VideInfraCMSBundle:Block:text.html.twig'
    vig.cms.textarea.block.template: 'VideInfraCMSBundle:Block:textarea.html.twig'
    vig.cms.editor.block.template: 'VideInfraCMSBundle:Block:editor.html.twig'
    vig.cms.editor.image.template: 'VideInfraCMSBundle:Block:image.html.twig'

services:

    vig.cms.page.repository:
        class: VideInfra\CMSBundle\Repository\PageRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: [ VideInfraCMSBundle:Page ]

    vig.cms.content.repository:
        class: VideInfra\CMSBundle\Repository\ContentRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: [ VideInfraCMSBundle:Content ]

    vig.cms.page.create.command:
        class: VideInfra\CMSBundle\Command\CreatePageCommand
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vig.cms.page.repository'
        tags:
            - { name: console.command }
        public: false

    vig.cms.page.loader:
        class: VideInfra\CMSBundle\Routing\PageLoader
        arguments:
            - '@vig.cms.page.manager'
        tags:
            - { name: routing.loader }

    vig.cms.custom_page.type:
        class: VideInfra\CMSBundle\Page\Type\CustomPageType
        tags:
            - { name: vig.page.type }

    vig.cms.simple_text.type:
        class: VideInfra\CMSBundle\Page\Type\SimpleTextPageType
        tags:
            - { name: vig.page.type }

    vig.cms.block.type:
        class: VideInfra\CMSBundle\Page\Type\BlockPageType
        tags:
            - { name: vig.page.type }

    vig.cms.text.block:
        class: VideInfra\CMSBundle\Page\Block\TextBlock
        arguments: ['%vig.cms.text.block.template%']
        tags:
            - { name: vig.block.type }

    vig.cms.textarea.block:
        class: VideInfra\CMSBundle\Page\Block\TextareaBlock
        arguments: ['%vig.cms.textarea.block.template%']
        tags:
            - { name: vig.block.type }

    vig.cms.editor.block:
        class: VideInfra\CMSBundle\Page\Block\EditorBlock
        arguments: ['%vig.cms.editor.block.template%']
        tags:
            - { name: vig.block.type }

    vig.cms.image.block:
        class: VideInfra\CMSBundle\Page\Block\ImageBlock
        arguments: ['%vig.cms.editor.image.template%']
        tags:
            - { name: vig.block.type }

    vig.cms.page.manager:
        class: VideInfra\CMSBundle\Service\PageManager
        arguments:
            - '@vig.cms.page.repository'
            - '@request_stack'

    vig.cms.block.manager:
        class: VideInfra\CMSBundle\Service\BlockManager
        arguments: ['@templating']

    vig.cms.page.factory:
        class: VideInfra\CMSBundle\Factory\PageFactory
        arguments:
            - '@vig.cms.page.manager'

    vig.cms.page.admin:
        class: VideInfra\CMSBundle\Admin\PageAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "CMS"
              label: "Pages"
              label_catalogue: "admin"
        arguments: [~, 'VideInfra\CMSBundle\Entity\Page', 'VideInfraCMSBundle:PageAdmin']
        calls:
            - [ 'setTemplate', ['list', 'VideInfraCMSBundle:Page:list.html.twig']]
            - [ 'setTranslationDomain', ['VideInfraCMSBundle']]
            - [ 'setPageManager', ['@vig.cms.page.manager']]
            - [ 'setAuthorizationChecker', ['@security.authorization_checker']]

    vig.cms.media.admin:
        class: VideInfra\CMSBundle\Admin\MediaAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "CMS"
              label: "Media"
              label_catalogue: "admin"
        arguments: [~, ~, 'VideInfraCMSBundle:Media']