parameters:

    octave.cms.super_admin_role: 'ROLE_SUPER_ADMIN'
    octave.cms.text_page_controller: 'OctaveCMSBundle:TextPage:show'
    octave.cms.text_page_template: 'OctaveCMSBundle:TextPage:show.html.twig'

    octave.cms.flexible_page_controller: 'OctaveCMSBundle:FlexiblePage:show'
    octave.cms.flexible_page_template: 'OctaveCMSBundle:FlexiblePage:show.html.twig'

    octave.cms.text.block.template: 'OctaveCMSBundle:Blocks:text.html.twig'
    octave.cms.textarea.block.template: 'OctaveCMSBundle:Blocks:textarea.html.twig'
    octave.cms.editor.block.template: 'OctaveCMSBundle:Blocks:editor.html.twig'
    octave.cms.image.block.template: 'OctaveCMSBundle:Blocks:image.html.twig'
    octave.cms.gallery.block.template: 'OctaveCMSBundle:Blocks:gallery.html.twig'

    octave.cms.page_use_versions: true

    locales: ['en']

services:

    # Repositories
    octave.cms.page.repository:
        class: Octave\CMSBundle\Repository\PageRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: [ OctaveCMSBundle:Page ]
        calls:
          - [ 'setTreeBuilder', ['@octave.cms.page.tree_builder']]

    octave.cms.content.repository:
        class: Octave\CMSBundle\Repository\ContentRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: [ OctaveCMSBundle:Content ]

    octave.cms.media_category.repository:
        class: Octave\CMSBundle\Repository\MediaCategoryRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: [ OctaveCMSBundle:MediaCategory ]
        calls:
          - [ 'setTreeBuilder', ['@octave.cms.media_category.tree_builder']]

    octave.cms.media_item.repository:
        class: Octave\CMSBundle\Repository\MediaItemRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: [ OctaveCMSBundle:MediaItem ]

    octave.cms.page_version.repository:
        class: Octave\CMSBundle\Repository\PageVersionRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: [ OctaveCMSBundle:PageVersion ]

    # Commands
    octave.cms.page.create.command:
        class: Octave\CMSBundle\Command\CreatePageCommand
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@octave.cms.page.repository'
        tags:
            - { name: console.command }
        public: false

    # Page types
    octave.cms.text_page.type:
        class: Octave\CMSBundle\Page\Type\TextPageType
        tags:
            - { name: octave.page.type }

    octave.cms.flexible_page.type:
        class: Octave\CMSBundle\Page\Type\FlexiblePageType
        tags:
            - { name: octave.page.type }

    octave.cms.custom_page.type:
        class: Octave\CMSBundle\Page\Type\CustomPageType
        tags:
            - { name: octave.page.type }

    # Blocks
    octave.cms.text.block:
        class: Octave\CMSBundle\Page\Block\TextBlock
        arguments: ['%octave.cms.text.block.template%']
        tags:
            - { name: octave.block.type }

    octave.cms.textarea.block:
        class: Octave\CMSBundle\Page\Block\TextareaBlock
        arguments: ['%octave.cms.textarea.block.template%']
        tags:
            - { name: octave.block.type }

    octave.cms.editor.block:
        class: Octave\CMSBundle\Page\Block\EditorBlock
        arguments: ['%octave.cms.editor.block.template%']
        tags:
            - { name: octave.block.type }

    octave.cms.image.block:
        class: Octave\CMSBundle\Page\Block\ImageBlock
        arguments: ['%octave.cms.image.block.template%']
        tags:
            - { name: octave.block.type }

    octave.cms.gallery.block:
        class: Octave\CMSBundle\Page\Block\GalleryBlock
        arguments: ['%octave.cms.gallery.block.template%']
        tags:
            - { name: octave.block.type }

    # Services
    octave.cms.page.manager:
        class: Octave\CMSBundle\Service\PageManager
        arguments:
            - '@octave.cms.page.repository'
            - '@request_stack'
            - '@security.authorization_checker'

    octave.cms.page.version.manager:
        class: Octave\CMSBundle\Service\PageVersionManager
        arguments:
            - '@octave.cms.page.manager'
            - '@octave.cms.page_version.repository'
            - '@doctrine.orm.entity_manager'

    octave.cms.block.manager:
        class: Octave\CMSBundle\Service\BlockManager
        arguments: ['@templating']

    octave.cms.page_type.factory:
        class: Octave\CMSBundle\Factory\PageTypeFactory
        arguments:
            - '@octave.cms.page.manager'

    octave.cms.image.processor:
        class: Octave\CMSBundle\Service\ImageProcessor
        arguments:
            - '%kernel.root_dir%'
            - '%octave.cms.media.upload_dir%'
            - '%octave.cms.media.resized_dir%'

    octave.cms.media_category.tree_builder:
        class: Octave\CMSBundle\Service\MediaCategoryTreeBuilder

    octave.cms.page.tree_builder:
        class: Octave\CMSBundle\Service\PageTreeBuilder
        arguments:
            - '@octave.cms.page.serializer'

    octave.cms.page.loader:
        class: Octave\CMSBundle\Routing\PageLoader
        arguments:
            - '@octave.cms.page.manager'
        tags:
            - { name: routing.loader }

    octave.cms.media_item.serializer:
        class: Octave\CMSBundle\Service\MediaItemSerializer

    octave.cms.page.serializer:
        class: Octave\CMSBundle\Service\PageSerializer
        arguments:
            - '@router'

    octave.cms.media_upload.helper:
        class: Octave\CMSBundle\Service\UploadHelper
        arguments:
            - '@octave.cms.media_item.repository'
            - '@octave.cms.media_item.manager'
            - '%octave.cms.media.upload_dir%'
            - '%kernel.root_dir%'

    octave.cms.media_item.manager:
        class: Octave\CMSBundle\Service\MediaItemManager
        arguments:
            - '%kernel.root_dir%'

    octave.cms.twig.extension:
        class: Octave\CMSBundle\Twig\CMSExtension
        arguments:
            - '@router'
            - '@service_container'
        tags:
            - { name: twig.extension }

    octave.cms.media_gallery_item.data_transformer.default:
        class: Octave\CMSBundle\Form\DataTransformer\MediaGalleryItemDataTransformer
        arguments: ['%locales%']

    octave.cms.media_image.data_transformer:
        class: Octave\CMSBundle\Form\DataTransformer\MediaImageDataTransformer
        arguments: ['%locales%']

    octave.cms.media_gallery.data_transformer.default:
        class: Octave\CMSBundle\Form\DataTransformer\MediaGalleryDataTransformer

    octave.cms.media_gallery_item.form_type:
        class: Octave\CMSBundle\Form\Type\MediaGalleryItemType
        arguments:
            - '@octave.cms.media_gallery_item.data_transformer'
        tags:
            - { name: form.type }

    octave.cms.block_image.form_type:
        class: Octave\CMSBundle\Form\Type\BlockImageType
        arguments:
           - '@octave.cms.media_image.data_transformer'
        tags:
            - { name: form.type }

    octave.cms.media_gallery.form_type:
        class: Octave\CMSBundle\Form\Type\MediaGalleryType
        arguments:
            - '@octave.cms.media_gallery.data_transformer'
        tags:
            - { name: form.type }

    # Admin
    octave.cms.sitemap.admin:
        class: Octave\CMSBundle\Admin\SitemapAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "CMS"
              label: "Sitemap"
              label_catalogue: "admin"
        arguments: [~, ~, 'OctaveCMSBundle:Sitemap']

    octave.cms.media.admin:
        class: Octave\CMSBundle\Admin\MediaAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "CMS"
              label: "Media"
              label_catalogue: "admin"
        arguments: [~, ~, 'OctaveCMSBundle:Media\Media']
        
    octave.cms.sitemap.source:
        class: Octave\CMSBundle\Service\SitemapSource
        arguments:
            - '@router'
            - '@octave.cms.page.repository'
            - '%octave.sitemap.host%'
        tags:
            - { name: octave.sitemap.source }