parameters:

    octave.cms.super_admin_role: 'ROLE_SUPER_ADMIN'
    octave.cms.text_page_controller: 'Octave\CMSBundle\Controller\TextPageController:showAction'
    octave.cms.text_page_template: '@@OctaveCMS\TextPage\show.html.twig'

    octave.cms.flexible_page_controller: 'Octave\CMSBundle\Controller\FlexiblePageController:showAction'
    octave.cms.flexible_page_template: '@@OctaveCMS\FlexiblePage\show.html.twig'

    octave.cms.text_line_editor.block.template: '@@OctaveCMS\Blocks\text_line_editor.html.twig'
    octave.cms.text_editor.block.template: '@@OctaveCMS\Blocks\text_editor.html.twig'
    octave.cms.rich_text_editor.block.template: '@@OctaveCMS\Blocks\rich_text_editor.html.twig'
    octave.cms.image.block.template: '@@OctaveCMS\Blocks\image.html.twig'
    octave.cms.gallery.block.template: '@@OctaveCMS\Blocks\gallery.html.twig'

    octave.cms.page_use_versions: true
    octave.cms.freeze_page_blocks_after_creation: false
    octave.cms.collapse_blocks_by_default: true

    octave.cms.media.resized_dir: ~

    locales: ['en']

    octave.sitemap.host: ~

services:

    # Repositories
    octave.cms.page.repository:
        class: Octave\CMSBundle\Repository\PageRepository
        public: true
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: [ Octave\CMSBundle\Entity\Page ]
        calls:
            - [ 'setTreeBuilder', ['@octave.cms.page.tree_builder']]

    octave.cms.content.repository:
        class: Octave\CMSBundle\Repository\ContentRepository
        public: true
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: [ Octave\CMSBundle\Entity\Content ]

    octave.cms.media_category.repository:
        class: Octave\CMSBundle\Repository\MediaCategoryRepository
        public: true
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: [ Octave\CMSBundle\Entity\MediaCategory ]
        calls:
            - [ 'setTreeBuilder', ['@octave.cms.media_category.tree_builder']]

    octave.cms.media_item.repository:
        class: Octave\CMSBundle\Repository\MediaItemRepository
        public: true
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: [ Octave\CMSBundle\Entity\MediaItem ]

    octave.cms.page_version.repository:
        class: Octave\CMSBundle\Repository\PageVersionRepository
        public: true
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: [ Octave\CMSBundle\Entity\PageVersion ]

    # Commands
    octave.cms.page.create.command:
        class: Octave\CMSBundle\Command\CreatePageCommand
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@octave.cms.page.repository'
        tags:
            - { name: console.command }
        public: false

    # Page types
    octave.cms.text_page.type:
        class: Octave\CMSBundle\Page\Type\TextPageType
        arguments:
            - '%locales%'
        tags:
            - { name: octave.page.type }

    octave.cms.flexible_page.type:
        class: Octave\CMSBundle\Page\Type\FlexiblePageType
        arguments:
            - '%locales%'
        tags:
            - { name: octave.page.type }

    octave.cms.custom_page.type:
        class: Octave\CMSBundle\Page\Type\CustomPageType
        arguments:
            - '%locales%'
        tags:
            - { name: octave.page.type }

    # Blocks
    octave.cms.text_line_editor.block:
        class: Octave\CMSBundle\Page\Block\TextLineEditorBlock
        arguments: ['%octave.cms.text_line_editor.block.template%']
        tags:
            - { name: octave.block.type }

    octave.cms.text_editor.block:
        class: Octave\CMSBundle\Page\Block\TextEditorBlock
        arguments: ['%octave.cms.text_editor.block.template%']
        tags:
            - { name: octave.block.type }

    octave.cms.rich_text_editor.block:
        class: Octave\CMSBundle\Page\Block\RichTextEditorBlock
        arguments: ['%octave.cms.rich_text_editor.block.template%']
        tags:
            - { name: octave.block.type }

    #    octave.cms.image.block:
    #        class: Octave\CMSBundle\Page\Block\ImageBlock
    #        arguments: ['%octave.cms.image.block.template%']
    #        tags:
    #            - { name: octave.block.type }
    #
    #    octave.cms.gallery.block:
    #        class: Octave\CMSBundle\Page\Block\GalleryBlock
    #        arguments: ['%octave.cms.gallery.block.template%']
    #        tags:
    #            - { name: octave.block.type }

    # Services
    octave.cms.page.manager:
        class: Octave\CMSBundle\Service\PageManager
        public: true
        arguments:
            - '@octave.cms.page.repository'
            - '@request_stack'
            - '@security.authorization_checker'
            - '%octave.cms.route_options%'

    octave.cms.page.version.manager:
        class: Octave\CMSBundle\Service\PageVersionManager
        public: true
        arguments:
            - '@octave.cms.page.manager'
            - '@octave.cms.page_version.repository'
            - '@doctrine.orm.entity_manager'

    octave.cms.block.manager:
        class: Octave\CMSBundle\Service\BlockManager
        public: true
        arguments: ['@twig']

    octave.cms.page_type.factory:
        class: Octave\CMSBundle\Factory\PageTypeFactory
        public: true
        arguments:
            - '@octave.cms.page.manager'

    octave.cms.image.processor:
        class: Octave\CMSBundle\Service\ImageProcessor
        arguments:
            - '%kernel.project_dir%'
            - '%octave.cms.media.upload_dir%'
            - '%octave.cms.media.resized_dir%'

    octave.cms.text.page.extension.manager:
        class: Octave\CMSBundle\Service\TextPageExtensionManager
        public: true

    octave.cms.media_category.tree_builder:
        class: Octave\CMSBundle\Service\MediaCategoryTreeBuilder

    octave.cms.page.tree_builder:
        class: Octave\CMSBundle\Service\PageTreeBuilder
        arguments:
            - '@octave.cms.page.serializer'
            - '@octave.cms.page.manager'

    octave.cms.page.loader:
        class: Octave\CMSBundle\Routing\PageLoader
        arguments:
            - '@octave.cms.page.manager'
        tags:
            - { name: routing.loader }

    octave.cms.media_item.serializer:
        class: Octave\CMSBundle\Service\MediaItemSerializer
        public: true
        arguments:
            - '%kernel.project_dir%'

    octave.cms.page.serializer:
        class: Octave\CMSBundle\Service\PageSerializer
        public: true
        arguments:
            - '@router'

    octave.cms.media_upload.helper:
        class: Octave\CMSBundle\Service\UploadHelper
        public: true
        arguments:
            - '@octave.cms.media_item.repository'
            - '@octave.cms.media_item.manager'
            - '%octave.cms.media.upload_dir%'
            - '%kernel.project_dir%'
            - '%octave.cms.media.allowed_mime_types%'

    octave.cms.media_item.manager:
        public: true
        class: Octave\CMSBundle\Service\MediaItemManager
        arguments:
            - '%kernel.project_dir%'

    octave.cms.twig.extension:
        class: Octave\CMSBundle\Twig\CMSExtension
        arguments:
            - '@router'
            - '@service_container'
        tags:
            - { name: twig.extension }

    octave.cms.media_gallery_item.data_transformer.default:
        class: Octave\CMSBundle\Form\DataTransformer\MediaGalleryItemDataTransformer
        arguments: ['%locales%']

    octave.cms.media_image.data_transformer:
        class: Octave\CMSBundle\Form\DataTransformer\MediaImageDataTransformer
        arguments: ['%locales%']

    octave.cms.media_gallery.data_transformer.default:
        class: Octave\CMSBundle\Form\DataTransformer\MediaGalleryDataTransformer

    octave.cms.media_gallery_item.form_type:
        class: Octave\CMSBundle\Form\Type\MediaGalleryItemType
        arguments:
            - '@octave.cms.media_gallery_item.data_transformer'
            - '%locales%'
        tags:
            - { name: form.type }

    octave.cms.block_collection.form_type:
        class: Octave\CMSBundle\Form\Type\BlockCollectionType
        arguments:
            - '%locales%'
        tags:
            - { name: form.type }

    octave.cms.block_image.form_type:
        class: Octave\CMSBundle\Form\Type\BlockImageType
        arguments:
            - '@octave.cms.media_image.data_transformer'
            - '%locales%'
        tags:
            - { name: form.type }

    octave.cms.block_item.form_type:
        class: Octave\CMSBundle\Form\Type\BlockItemType
        arguments:
            - '%locales%'
        tags:
            - { name: form.type }

    octave.cms.blocks.form.type:
        class: Octave\CMSBundle\Form\Type\BlocksType
        arguments:
            - '@octave.cms.block.manager'
            - '%locales%'
        tags:
            - { name: form.type }

    octave.cms.media_gallery.form_type:
        class: Octave\CMSBundle\Form\Type\MediaGalleryType
        arguments:
            - '@octave.cms.media_gallery.data_transformer'
            - '%locales%'
        tags:
            - { name: form.type }

    octave.cms.media_image.form_type:
        class: Octave\CMSBundle\Form\Type\MediaImageType
        arguments:
            - '%locales%'
        tags:
            - { name: form.type }

    octave.cms.media_file.form_type:
        class: Octave\CMSBundle\Form\Type\MediaFileType
        arguments:
            - '%locales%'
        tags:
            - { name: form.type }

    octave.cms.simple_text_content.form_type:
        class: Octave\CMSBundle\Form\Type\SimpleTextContentType
        arguments:
            - '%locales%'
        tags:
            - { name: form.type }

    octave.cms.sitemap.source:
        class: Octave\CMSBundle\Service\SitemapSource
        arguments:
            - '@router'
            - '@octave.cms.page.repository'
            - '%octave.sitemap.host%'
            - '%locales%'
        tags:
            - { name: octave.sitemap.source }

    sonata.admin.request.fetcher:
        class: Sonata\AdminBundle\Request\AdminFetcher
        public: true
        arguments:
            - '@sonata.admin.pool'

    # Controller
    Octave\CMSBundle\Controller\PageController:
        tags:
            - { name: controller.service_arguments }
        calls:
            - [setContainer, ['@service_container']]

    Octave\CMSBundle\Controller\FlexiblePageController:
        tags:
            - { name: controller.service_arguments }
        calls:
            - [setContainer, ['@service_container']]

    Octave\CMSBundle\Controller\CustomPageController:
        tags:
            - { name: controller.service_arguments }
        calls:
            - [setContainer, ['@service_container']]

    Octave\CMSBundle\Controller\SitemapController:
        tags:
            - { name: controller.service_arguments }
        calls:
            - [setContainer, ['@service_container']]

    Octave\CMSBundle\Controller\Media\MediaController:
        tags:
            - { name: controller.service_arguments }
        calls:
            - [setContainer, ['@service_container']]
            -
    Octave\CMSBundle\Controller\Media\ItemController:

        tags:
            - { name: controller.service_arguments }
        calls:
            - [setContainer, ['@service_container']]
    Octave\CMSBundle\Controller\Media\CategoryController:
        tags:
            - { name: controller.service_arguments }
        calls:
            - [setContainer, ['@service_container']]

    # Admin
    octave.cms.sitemap.admin:
        class: Octave\CMSBundle\Admin\SitemapAdmin
        tags:
            - name: sonata.admin
              model_class: Octave\CMSBundle\Entity\Page
              controller: Octave\CMSBundle\Controller\SitemapController
              manager_type: orm
              group: "CMS"
              label: "label.admin.sitemap"
              label_catalogue: "OctaveCMSBundle"
        calls:
            - [ 'setTranslationDomain', ['OctaveCMSBundle']]

    octave.cms.media.admin:
        class: Octave\CMSBundle\Admin\MediaAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "CMS"
              label: "label.admin.media"
              label_catalogue: "SonataAdminBundle"
        arguments: [~, 'Octave\\CMSBundle\\Entity\\MediaItem', Octave\CMSBundle\Controller\Media\MediaController]
        calls:
            - [ 'setTranslationDomain', ['OctaveCMSBundle']]