parameters:

    vig.cms.super_admin_role: 'ROLE_SUPER_ADMIN'
    vig.cms.simple_text_controller: 'VideInfraCMSBundle:SimpleText:show'
    vig.cms.simple_text_template: 'VideInfraCMSBundle:SimpleText:show.html.twig'

    vig.cms.block_controller: 'VideInfraCMSBundle:Block:show'
    vig.cms.block_template: 'VideInfraCMSBundle:Block:show.html.twig'
    vig.cms.text.block.template: 'VideInfraCMSBundle:Block:text.html.twig'
    vig.cms.textarea.block.template: 'VideInfraCMSBundle:Block:textarea.html.twig'
    vig.cms.editor.block.template: 'VideInfraCMSBundle:Block:editor.html.twig'
    vig.cms.image.block.template: 'VideInfraCMSBundle:Block:image.html.twig'
    vig.cms.gallery.block.template: 'VideInfraCMSBundle:Block:gallery.html.twig'
    locales: ['en']

services:

    # Repositories
    vig.cms.page.repository:
        class: VideInfra\CMSBundle\Repository\PageRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: [ VideInfraCMSBundle:Page ]
        calls:
          - [ 'setTreeBuilder', ['@vig.cms.page.tree_builder']]

    vig.cms.content.repository:
        class: VideInfra\CMSBundle\Repository\ContentRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: [ VideInfraCMSBundle:Content ]

    vig.cms.media_category.repository:
        class: VideInfra\CMSBundle\Repository\MediaCategoryRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: [ VideInfraCMSBundle:MediaCategory ]
        calls:
          - [ 'setTreeBuilder', ['@vig.cms.media_category.tree_builder']]

    vig.cms.media_item.repository:
        class: VideInfra\CMSBundle\Repository\MediaItemRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: [ VideInfraCMSBundle:MediaItem ]

    vig.cms.page_version.repository:
        class: VideInfra\CMSBundle\Repository\PageVersionRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: [ VideInfraCMSBundle:PageVersion ]

    # Commands
    vig.cms.page.create.command:
        class: VideInfra\CMSBundle\Command\CreatePageCommand
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vig.cms.page.repository'
        tags:
            - { name: console.command }
        public: false

    # Page types
    vig.cms.simple_text.type:
        class: VideInfra\CMSBundle\Page\Type\SimpleTextPageType
        tags:
            - { name: vig.page.type }

    vig.cms.block.type:
        class: VideInfra\CMSBundle\Page\Type\BlockPageType
        tags:
            - { name: vig.page.type }

    vig.cms.custom_page.type:
        class: VideInfra\CMSBundle\Page\Type\CustomPageType
        tags:
            - { name: vig.page.type }

    # Blocks
    vig.cms.text.block:
        class: VideInfra\CMSBundle\Page\Block\TextBlock
        arguments: ['%vig.cms.text.block.template%']
        tags:
            - { name: vig.block.type }

    vig.cms.textarea.block:
        class: VideInfra\CMSBundle\Page\Block\TextareaBlock
        arguments: ['%vig.cms.textarea.block.template%']
        tags:
            - { name: vig.block.type }

    vig.cms.editor.block:
        class: VideInfra\CMSBundle\Page\Block\EditorBlock
        arguments: ['%vig.cms.editor.block.template%']
        tags:
            - { name: vig.block.type }

    vig.cms.image.block:
        class: VideInfra\CMSBundle\Page\Block\ImageBlock
        arguments: ['%vig.cms.image.block.template%']
        tags:
            - { name: vig.block.type }

    vig.cms.gallery.block:
        class: VideInfra\CMSBundle\Page\Block\GalleryBlock
        arguments: ['%vig.cms.gallery.block.template%']
        tags:
            - { name: vig.block.type }

    # Services
    vig.cms.page.manager:
        class: VideInfra\CMSBundle\Service\PageManager
        arguments:
            - '@vig.cms.page.repository'
            - '@request_stack'
            - '@security.authorization_checker'

    vig.cms.page.version.manager:
        class: VideInfra\CMSBundle\Service\PageVersionManager
        arguments:
            - '@vig.cms.page.manager'
            - '@vig.cms.page_version.repository'
            - '@doctrine.orm.entity_manager'

    vig.cms.block.manager:
        class: VideInfra\CMSBundle\Service\BlockManager
        arguments: ['@templating']

    vig.cms.page_type.factory:
        class: VideInfra\CMSBundle\Factory\PageTypeFactory
        arguments:
            - '@vig.cms.page.manager'

    vig.cms.media_category.tree_builder:
        class: VideInfra\CMSBundle\Service\MediaCategoryTreeBuilder

    vig.cms.page.tree_builder:
        class: VideInfra\CMSBundle\Service\PageTreeBuilder
        arguments:
            - '@vig.cms.page.serializer'

    vig.cms.page.loader:
        class: VideInfra\CMSBundle\Routing\PageLoader
        arguments:
            - '@vig.cms.page.manager'
        tags:
            - { name: routing.loader }

    vig.cms.media_item.serializer:
        class: VideInfra\CMSBundle\Service\MediaItemSerializer

    vig.cms.page.serializer:
        class: VideInfra\CMSBundle\Service\PageSerializer
        arguments:
            - '@router'

    vig.cms.media_upload.helper:
        class: VideInfra\CMSBundle\Service\UploadHelper
        arguments:
            - '@vig.cms.media_item.repository'
            - '@vig.cms.media_item.manager'
            - '%vig.cms.media.upload_dir%'
            - '%kernel.root_dir%'

    vig.cms.media_item.manager:
        class: VideInfra\CMSBundle\Service\MediaItemManager
        arguments:
            - '%kernel.root_dir%'

    vig.cms.twig.extension:
        class: VideInfra\CMSBundle\Twig\CMSExtension
        arguments:
            - '@router'
            - '@service_container'
        tags:
            - { name: twig.extension }

    vig.cms.media_gallery_item.data_transformer.default:
        class: VideInfra\CMSBundle\Form\DataTransformer\MediaGalleryItemDataTransformer
        arguments: ['%locales%']

    vig.cms.media_gallery.data_transformer.default:
        class: VideInfra\CMSBundle\Form\DataTransformer\MediaGalleryDataTransformer

    vig.cms.media_gallery_item.form_type:
        class: VideInfra\CMSBundle\Form\Type\MediaGalleryItemType
        arguments:
            - '@vig.cms.media_gallery_item.data_transformer'
        tags:
            - { name: form.type }

    vig.cms.media_gallery.form_type:
        class: VideInfra\CMSBundle\Form\Type\MediaGalleryType
        arguments:
            - '@vig.cms.media_gallery.data_transformer'
        tags:
            - { name: form.type }

    # Admin
    vig.cms.sitemap.admin:
        class: VideInfra\CMSBundle\Admin\SitemapAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "CMS"
              label: "Sitemap"
              label_catalogue: "admin"
        arguments: [~, ~, 'VideInfraCMSBundle:Sitemap']

    vig.cms.media.admin:
        class: VideInfra\CMSBundle\Admin\MediaAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "CMS"
              label: "Media"
              label_catalogue: "admin"
        arguments: [~, ~, 'VideInfraCMSBundle:Media\Media']
        
    vig.cms.sitemap.source:
        class: VideInfra\CMSBundle\Service\SitemapSource
        arguments:
            - '@router'
            - '@vig.cms.page.repository'
            - '%vig.sitemap.host%'
        tags:
            - { name: vig.sitemap.source }